bases:
  #   - "../../bases/client"
  - "../../bases/pg"
#   - "../../bases/db"
#   - "../../bases/server"

# patchesStrategicMerge:
#   - "db-migration.yaml"

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: db-initialize-configmap
    files:
      - init.sql

namespace: starter
