apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  labels:
    app: client
spec:
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      restartPolicy: Always
      containers:
        - name: client
          image: starter/client-dev
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: dev-env-configmap
          resources:
            limits:
              cpu: "400m"
              memory: "800Mi"
